Download and Incorporate PTC Capability
bssw-psip/ptc-catalog pull request #50
Opened 2022-07-18 18:21 UTC by mrmundt

This PR has several changes:

- Move scripts to `assets` directory (with styles and images)
- Add a script and GitHub Action to insert `Download this PTC` capability to all new cards
- Create blank "Progress Tracking Card Template" for the catalog
- Add instructions with examples on how to download and incorporate PTCs into GitHub and GitLab projects
- Add a "Using the Catalog" summary on the index page

2022-07-18 18:22 UTC, mrmundt commented
I have a test site of this available at: https://mrmundt.github.io/ptc-catalog/

2022-07-18 19:26 UTC, killillian reviewed
Everything looks great! I think the download links are very useful, and navigating the pages was easy and intuitive. The examples were also very helpful, especially since they documented both GitHub and GitLab GUIs. I noticed two very small typos that I commented on in-line, but otherwise no issues!

2022-07-18 19:26 UTC, killillian commented on catalog/ProgressTrackingCardTemplate.md
> +Any comments additional comments here.
I think this is just meant to say "Any additional comments here."

2022-07-18 19:31 UTC, killillian approved these changes
Looks good to me!

2022-07-27 16:50 UTC, mrmundt commented
Ping @elaineraybourn @wtsutherland @rmmilewi @gonsie

2022-07-28 22:33 UTC, elaineraybourn commented on catalog/ProgressTrackingCardTemplate.md
> +| Score         | Description |
We discussed changing "score" to "Stage" or something that does not suggest assessment. Does it make sense to change this here?

2022-07-28 22:36 UTC, elaineraybourn requested changes
HI @mrmundt very nice, just change the reference to score that I made in my comment and we are good to go.

2022-08-10 14:25 UTC, merged